// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteAspNetCoreDemo;

namespace SQLiteAspNetCoreDemo.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    [Migration("20201111033321_TableTeamAndMembership")]
    partial class TableTeamAndMembership
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SQLiteAspNetCoreDemo.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SQLiteAspNetCoreDemo.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameTeam")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("SQLiteAspNetCoreDemo.TeamMembership", b =>
                {
                    b.Property<int>("TeamMembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamMembershipId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembership");
                });

            modelBuilder.Entity("SQLiteAspNetCoreDemo.TeamMembership", b =>
                {
                    b.HasOne("SQLiteAspNetCoreDemo.Employee", null)
                        .WithMany("TeamMembership")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("SQLiteAspNetCoreDemo.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SQLiteAspNetCoreDemo.Employee", b =>
                {
                    b.Navigation("TeamMembership");
                });
#pragma warning restore 612, 618
        }
    }
}
